# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd69a63c036cd72cc86b46327e0e662d694068cd68d0c05cda679f7f58ad7b7d2017062ae08c3ccc7fb213c6235d76ca06e20407e78c99d0865c41ebdfbcd9c5

test:
  secret_key_base: e5e2dd76b5c6dbc7e949c9433c1a8aaea4c97705dc998b6beb90612805c74b0cdeb613dfaf0552b9cecd30e49e5280f9e156b25cdcf67f6d03191e34ca9730b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
